---

features:
  - title: YAML structure
    includes:
    - title: Engine configuration
    - title: Binary
    - title: Variable
    - title: Domain
    - title: Task
    - title: Step
    - title: Task step
    - title: Shell step
    - title: Finally section for the task
    - title: Parameter for the task
    tasks:
      - title: declaration
      - title: schema
      - title: shell test
  - title: File structure
    includes:
      - title: Naming convention
      - title: developer mode
      - title: continuous integration mode
  - title: Template
    includes:
      - title: render run
      - title: render if and unless
      - title: render title and description
  - title: Command
    includes:
      - title: run simple command
      - title: run command with parameters validation
      - title: run multiple shells
      - title: run with schema validation
  - title: Help
    includes:
      - title: overall help
      - title: help for domain
      - title: help for task
      - title: help for schema
      - title: help for binaries
  - title: Diagnosis
    includes:
      - title: validate schema
      - title: validate build with schema
      - title: check binaries support
      - title: check file structure
      - title: validate templates
      - title: check telemetry paths
  - title: Telemetry
    includes:
      - title: append telemetry records to db
      - title: reset all telemetry
      - title: reset telemetry by name
