---
model:
  githubAccount: github-account-fixme
  projectName: project-name-fixme
  copyright:
    holder: copyright-holder-fixme
    startYear: 2022
  license: BSD3
  project_yaml: script/data/project.yaml
  project_schema: './script/schema/project.schema.json'
  generate_sh: script/generate.sh
  colors:
    - green
    - orange
    - blue
  animals:
    - cat
    - dog
workflows:
  test:
    title: Test your library
    description: Test your library for defects
    tasks:
      generate:
        title: Generate code
        description: Generate code
        motivation: Generate code
        parameters:
          color:
            description: Color
            flags: '-c, --color <type>'
        steps:
          - a: batch
            name: calculate
            title: Run calculate
            before:
              - a: get-property
                name: githubAccount
                title: Set variable githubAccount
                value: build.model.githubAccount
              - a: get-property
                name: githubAccount2
                title: Set variable githubAccount
                value: data.test::generate::githubAccount
            commands:
              - name: first
                title: First echo
                run: echo "First is {{data.status}} and {{data.test::generate::githubAccount}} and {{build.model.license}}"
              - name: second
                title: Second echo with task.name
                run: echo "Second {{task.name}}"
                onSuccess:
                  - trim
                onFailure:
                  - exit
      lint:
        title: Lint code
        description: Lint code
        motivation: Lint code
        parameters: {}
        steps:
          - a: batch
            name: list files
            title: List files
            commands:
              - name: list source files
                run: yarn lint